export {
  DEFAULT_BASE_RATE,
  calculateQuote,
  computeQuoteTotal,
  getDefaultCalcConfig,
  mergeCalcBreakdowns,
  mergeCalcConfigWithDefaults,
  type CalcConfig,
  type CalcBreakdown,
  type CalcInput,
  type CalcIssue,
  type CalcLineItem,
  type CalcResultDTO,
  type GlassOptionsInput,
  type HandleSide,
  type HardwareOptionCatalogItem,
  type LaminationColor,
  type OpeningType,
  type OptionPrice,
  type ProfileModelCatalogItem,
  type SashOpening,
  type WindowGeometryConfig,
  calculateVolumeDiscount,
  DEFAULT_VOLUME_DISCOUNT,
  type VolumeDiscountConfig,
  type VolumeDiscountResult,
  type VolumeDiscountTier,
} from "window-door-store-calc-engine";
